### ISSUE TITLE
Not working after HA upgrade to 2021.10.01

### ISSUE THREAD

**Issue by scaarup** [mdegat01/addon-promtail#149]
**Describe the bug**
The addon is no longer able to start, after upgrading HA. The log below is all I got. I am not sure if it is capped.

**Logs**

```
	/src/loki/clients/pkg/logentry/stages/multiline.go:109 +0x9c
created by github.com/grafana/loki/clients/pkg/logentry/stages.(*multilineStage).Run
	/src/loki/clients/pkg/logentry/stages/multiline.go:103 +0x50
goroutine 76 [chan receive]:
github.com/grafana/loki/clients/pkg/logentry/stages.(*matcherStage).runKeep.func1(0x5594dc0, 0x5594e40)
	/src/loki/clients/pkg/logentry/stages/match.go:160 +0x9c
created by github.com/grafana/loki/clients/pkg/logentry/stages.(*matcherStage).runKeep
	/src/loki/clients/pkg/logentry/stages/match.go:158 +0x8c
goroutine 77 [chan receive]:
github.com/grafana/loki/clients/pkg/logentry/stages.(*matcherStage).runKeep.func2(0x5594d80, 0x5594d40, 0x54a5710, 0x5594dc0)
	/src/loki/clients/pkg/logentry/stages/match.go:166 +0x60
created by github.com/grafana/loki/clients/pkg/logentry/stages.(*matcherStage).runKeep
	/src/loki/clients/pkg/logentry/stages/match.go:164 +0xc0
goroutine 78 [chan receive]:
github.com/grafana/loki/clients/pkg/logentry/stages.(*Pipeline).Wrap.func1(0x54c9610, 0x5594dc0, 0x5594780)
	/src/loki/clients/pkg/logentry/stages/pipeline.go:101 +0x8c
created by github.com/grafana/loki/clients/pkg/logentry/stages.(*Pipeline).Wrap
	/src/loki/clients/pkg/logentry/stages/pipeline.go:99 +0x104
goroutine 79 [chan receive]:
github.com/grafana/loki/clients/pkg/logentry/stages.(*Pipeline).Wrap.func2(0x54c9610, 0x5594d00, 0x5594cc0)
	/src/loki/clients/pkg/logentry/stages/pipeline.go:108 +0xc8
created by github.com/grafana/loki/clients/pkg/logentry/stages.(*Pipeline).Wrap
	/src/loki/clients/pkg/logentry/stages/pipeline.go:105 +0x130
goroutine 80 [runnable]:
github.com/coreos/go-systemd/sdjournal._Cfunc_my_sd_journal_next(0x63bc4629, 0x65802b48)
	_cgo_gotypes.go:318 +0x34
github.com/coreos/go-systemd/sdjournal.(*Journal).Next.func1(0x63bc4629, 0x54c98a0)
	/src/loki/vendor/github.com/coreos/go-systemd/sdjournal/journal.go:561 +0x7c
github.com/coreos/go-systemd/sdjournal.(*Journal).Next(0x54c98a0)
	/src/loki/vendor/github.com/coreos/go-systemd/sdjournal/journal.go:561 +0x6c
github.com/coreos/go-systemd/sdjournal.(*JournalReader).Read(0x54bb170, {0x56ce000, 0x10000, 0x10000})
	/src/loki/vendor/github.com/coreos/go-systemd/sdjournal/read.go:142 +0x34
github.com/coreos/go-systemd/sdjournal.(*JournalReader).Follow(0x54bb170, 0x5594e80, {0x26d52e0, 0x3857bf0})
	/src/loki/vendor/github.com/coreos/go-systemd/sdjournal/read.go:210 +0xb8
github.com/grafana/loki/clients/pkg/promtail/targets/journal.journalTargetWithReader.func1(0x541fec0, 0x5594e80)
	/src/loki/clients/pkg/promtail/targets/journal/journaltarget.go:181 +0x48
created by github.com/grafana/loki/clients/pkg/promtail/targets/journal.journalTargetWithReader
	/src/loki/clients/pkg/promtail/targets/journal/journaltarget.go:179 +0x3c8
goroutine 102 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/weaveworks/common/server.(*Server).Run
	/src/loki/vendor/github.com/weaveworks/common/server/server.go:383 +0x4c
goroutine 103 [IO wait]:
internal/poll.runtime_pollWait(0x65914b88, 0x72)
	/usr/local/go/src/runtime/netpoll.go:229 +0xac
internal/poll.(*pollDesc).wait(0x5754154, 0x72, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x5754140)
	/usr/local/go/src/internal/poll/fd_unix.go:402 +0x234
net.(*netFD).accept(0x5754140)
	/usr/local/go/src/net/fd_unix.go:173 +0x20
net.(*TCPListener).accept(0x54bb6b0)
	/usr/local/go/src/net/tcpsock_posix.go:140 +0x20
net.(*TCPListener).Accept(0x54bb6b0)
	/usr/local/go/src/net/tcpsock.go:262 +0x30
github.com/weaveworks/common/middleware.(*countingListener).Accept(0x54bb6d0)
	/src/loki/vendor/github.com/weaveworks/common/middleware/counting_listener.go:22 +0x28
net/http.(*Server).Serve(0x5616630, {0x26f07d4, 0x54bb6d0})
	/usr/local/go/src/net/http/server.go:3001 +0x320
github.com/weaveworks/common/server.(*Server).Run.func2(0x562cd80, 0x5697600)
	/src/loki/vendor/github.com/weaveworks/common/server/server.go:394 +0x80
created by github.com/weaveworks/common/server.(*Server).Run
	/src/loki/vendor/github.com/weaveworks/common/server/server.go:391 +0x70
trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0x64ffd9b4
r2      0x0
r3      0x8
r4      0x0
r5      0x64ffd9b4
r6      0x1
r7      0xaf
r8      0x5490000
r9      0xf0
r10     0x54920f0
fp      0x37c10f4
ip      0xaf
sp      0x64ffd9a8
lr      0x76e28ea1
pc      0x76e19c66
cpsr    0x70030
fault   0x0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Environment (please complete the following information):**

- Add-on version: 1.8.1
- Supervisor version: 2021.09.6
- Operating system: Home Assistant OS 6.4

**Comment by mdegat01** [comment]
There hasn't been any activity on this issue recently, so we clean up some of the older and inactive issues. Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by leaving a comment 👍 This issue has now been marked as stale and will be closed if no further activity occurs. Thanks!
